#!/bin/bash

A=100000
B=1000000
C=80000
KIND=ipv4

ERROR=0.2
ERROR2=0.0001

A_PATH=work/A.txt
B_PATH=work/B.txt
C_PATH=work/C.txt
K_PATH=work/K.txt

python3 gen.py $A $B $C $KIND
./cleanroom create    work/mm -i $A_PATH -v -k $K_PATH --error $ERROR --error2 $ERROR2
./cleanroom intersect work/mm -i $B_PATH -v -k $K_PATH -o $C_PATH -r $A_PATH
